cells=c(1,3,5,7,8,9,11,12,14)
rnames=c("Row1","Row2","Row3")
cnames=c("Col1","Col2","Col3")
m2=matrix(cells,nrow=3,ncol=3,byrow=TRUE,dimnames=list(rnames,cnames))
print("3 X 3 matrix with labels , filled by  rows :")
print(m2)
print("3 X 3 matrix with labels , filled by columns :")
m2=matrix(cells,nrow=3,ncol=3,byrow=FALSE,dimnames=list(rnames,cnames))
print(m2)